name: gta vi
on: 
push:
branches: [main]
jobs:
deploy:
runs-on: ubuntu-latest
steps: 
- uses: actions/checkout@v3
- name: node.setup
with: 
node-version: 18
- name: install-moduls
run: npm install
- name: npm run build
- name: deploy to github pages
uses: peaceiris/actions-gh-pages@v3
with: 
github_token: ${{secrets.GITHUB_TOKEN}}
publish_dir: ./dist